In [1]:
import numpy as np
arr_1 = np.full((3, 4), 3)
print("arr_1:")
print(arr_1)
arr_2 = np.random.randint(0, 10, size=(2, 4))
print("arr_2:")
print(arr_2)
print("Количество элементов в arr_1:", arr_1.size)
print("Количество элементов в arr_2:", arr_2.size)

arr_1:
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
arr_2:
[[0 0 1 2]
 [5 0 5 6]]
Количество элементов в arr_1: 12
Количество элементов в arr_2: 8


In [2]:
arr_concatenated = np.concatenate((arr_1, arr_2), axis=0)
print("arr_concatenated:")
print(arr_concatenated)

arr_concatenated:
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [0 0 1 2]
 [5 0 5 6]]


In [3]:
arr_3 = np.array((1, 8, 6, 5, 8, 3))
print("arr_3:")
print(arr_3)

arr_3:
[1 8 6 5 8 3]


In [4]:
print(*arr_3)

1 8 6 5 8 3


In [5]:
arr_4 = arr_3 * 3 + 1
print("arr_4:")
print(*arr_4)

arr_4:
4 25 19 16 25 10


In [6]:
arr_5 = arr_3.reshape(2, 3)
print("arr_5:")
print(*arr_5)

arr_5:
[1 8 6] [5 8 3]


In [7]:
arr5_min = np.min(arr_5, axis=1)
print("Минимальные элементы вдоль первой оси в arr_5:", arr5_min)

Минимальные элементы вдоль первой оси в arr_5: [1 3]


In [8]:
arr5_mean = np.mean(arr_5)
print("Среднее арифметическое всех элементов в arr_5:", round(arr5_mean, 2))


Среднее арифметическое всех элементов в arr_5: 5.17


In [9]:
arr_6 = np.square(np.arange(11))
print("arr_6:")
print(arr_6)

arr_6:
[  0   1   4   9  16  25  36  49  64  81 100]


In [10]:
print("Каждый второй элемент arr_6:", arr_6[::2])

Каждый второй элемент arr_6: [  0   4  16  36  64 100]


In [11]:
print("Элементы arr_6 в обратном порядке:", arr_6[::-1])

Элементы arr_6 в обратном порядке: [100  81  64  49  36  25  16   9   4   1   0]


In [12]:
arr_6[1::2] = 2
print("arr_6:")
print(arr_6)

arr_6:
[  0   2   4   2  16   2  36   2  64   2 100]


In [13]:
arr6_has_49 = np.any(arr_6 == 49)
print(" 49?\n",arr6_has_49)

 49?
 False


In [14]:
A = np.array([[1, -2, 3], [-4, 5, -6], [7, -8, 9]])
print("Массив A:")
print(*A)

Массив A:
[ 1 -2  3] [-4  5 -6] [ 7 -8  9]


In [15]:
B = A[A < 0]
print("Массив B с отрицательными элементами:")
print(B)

Массив B с отрицательными элементами:
[-2 -4 -6 -8]
